apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-booking-deployment
  labels:
    app: bus-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bus-booking
  template:
    metadata:
      labels:
        app: bus-booking
    spec:
      containers:
        - name: bus-booking
          image: docker.io/paal2004/bus-booking:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
